<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">
    
    <xsl:key name="users" match="order" use="user" />
    <!-- "/" indicate that template is applied to the root node of xml file -->
    <xsl:template match="/">
        <html>
            <head>
                <title>Potential User Report</title>
                <link rel="stylesheet" type="text/css" href="../../config/site_css_links.php"/>
                <style>
                    table {
                    text-align: center;
                    border-collapse: collapse;
                    width: 100%;
                    font-family: Calibri, sans-serif;
                    }

                    th, td {
                    background-color:white;
                    padding: 8px;
                    border: 1px solid black;
                    }

                    th { 
                    font-weight: bold;
                    }

                    h2, small {
                    font-family: Calibri, sans-serif;
                    }
                    
                    small{
                    font-weight: bold;
                    }
                </style>
            </head>
            <body>
                <h2>Top 5 most potential user</h2>
                <table border="1">
                    <tr>
                        <th>No.</th>
                        <th>User Name</th>
                        <th>Total Payment Made</th>
                        <th>Total Order Made</th>
                    </tr>
                    <!-- Declare a variable to store the counter value -->
                    <xsl:variable name="counter" select="0"/>
                    <!-- Use for each loop to iterate the role element inside the 
                    root tag   -->
                    <xsl:for-each select="//order[generate-id(.)=generate-id(key('users', user)[1])]">
                        <xsl:sort select="sum(key('users', user)/price)" order="descending" />
                        <xsl:if test="position() &lt;= 5">
                            <tr>
                                <td>
                                    <!-- Use the position() function to get the current position
                                    and add the counter value to it -->
                                    <xsl:value-of select="$counter + position()"/>
                                </td>
                            
                                <td>
                                    <!-- retrieve the value of "id" element
                                    from xml file -->
                                    <xsl:value-of select="user"/>
                                </td>
                            
                                <td>
                                    <xsl:value-of select="sum(key('users', user)/price)"/>
                                </td>
                            
                                <td>
                                    <xsl:value-of select="count(key('users', user))"/>
                                </td>
                            </tr>
                        </xsl:if>
                    </xsl:for-each>
                </table>
                <footer>
                    <small>Generated by Japanese Online Ticketing System</small>
                </footer>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
