<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">
    <!-- "/" indicate that template is applied to the root node of xml file -->
    <xsl:template match="/">
        <html>
            <head>
                <title>Roles</title>
                <link rel="stylesheet" type="text/css" href="../../config/site_css_links.php"/>
                <style>
                    table {
                    text-align: center;
                    border-collapse: collapse;
                    width: 100%;
                    font-family: Calibri, sans-serif;
                    }

                    th, td {
                    background-color:white;
                    padding: 8px;
                    border: 1px solid black;
                    }

                    th { 
                    font-weight: bold;
                    }

                    h2, small {
                    font-family: Calibri, sans-serif;
                    }
                    
                    small{
                    font-weight: bold;
                    }
                </style>
            </head>
            <body>
                <h2>Roles</h2>
                <table border="1">
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                    </tr>
                    <!-- Use for each loop to iterate the role element inside the 
                    root tag   -->
                    <xsl:for-each select="Roles/role">
                        <tr>
                            <td>
                                <!-- retrieve the value of "id" element
                                from xml file -->
                                <xsl:value-of select="id"/>
                            </td>
                            
                            <td>
                                <xsl:value-of select="title"/>
                            </td>
                        </tr>
                    </xsl:for-each>
                </table>
                <footer>
                    <small>Generated by Japanese Online Ticketing System</small>
                </footer>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
