<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">
    <!-- "/" indicate that template is applied to the root node of xml file -->
    <xsl:template match="/">
        <html>
            <head>
                <title>Sales Report</title>
                <link rel="stylesheet" type="text/css" href="../../config/site_css_links.php"/>
                <style>
                    table {
                    text-align: center;
                    border-collapse: collapse;
                    width: 100%;
                    font-family: Calibri, sans-serif;
                    }

                    th, td {
                    background-color:white;
                    padding: 8px;
                    border: 1px solid black;
                    }

                    th { 
                    font-weight: bold;
                    }

                    h2, small {
                    font-family: Calibri, sans-serif;
                    }
                    
                    small{
                    font-weight: bold;
                    }
                </style>
            </head>
            <body>
                <h2>Top 5 Highest Earning Events</h2>
                <table border="1">
                    <tr>
                        <th>No.</th>
                        <th>Event Name</th>
                        <th>Category</th>
                        <th>Total Revenue</th>
                    </tr>
                    <!-- Declare a variable to store the counter value -->
                    <xsl:variable name="counter" select="0"/>
                    
                    <xsl:for-each select="Event/event">
                        <xsl:sort select="price * (capacity - quantityLeft)" order="descending"/>
                        <xsl:if test="position() &lt;= 5">
                            <tr>
                                <td>
                                    <!-- Use the position() function to get the current position
                                    and add the counter value to it -->
                                    <xsl:value-of select="$counter + position()"/>
                                </td>
                            
                                <td>
                                    <!-- retrieve the value of "id" element
                                    from xml file -->
                                    <xsl:value-of select="name"/>
                                </td>
                            
                                <td>
                                    <xsl:value-of select="category"/>
                                </td>
                            
                                <td>
                                    <xsl:value-of select="price * (capacity - quantityLeft)"/>
                                </td>
                            </tr>
                        </xsl:if>
                    </xsl:for-each>
                </table>
                <footer>
                    <small>Generated by Japanese Online Ticketing System</small>
                </footer>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
